const data = {playList: [
{author:"Snoop Doggy Dogg & The Doors",song:"Riders On The Storm (Fredwreck Remix)",year:"2001",genre:""},
{author:"Ida Corr vs Fedde Le Grand",song:"Let me think about it (original mix)",year:"1999",genre:"Dance"},
{author:"Chad Croeger & Josey Scott",song:"Hero",year:"2006",genre:"Soundtrack"},
{author:"Iris",song:"Goo Goo Dols",year:"2006",genre:"Rock"},
{author:"Reamon",song:"Supergirl (album version)",year:"2006",genre:"Rock"},
{author:"Sting",song:"Desert rose",year:"2006",genre:""},
{author:"Robbie Williams",song:"Feel",year:"2010",genre:"Pop"},
{author:"Alicia Keys",song:"A Woman's Worth",year:"2008",genre:"General R&B"},
{author:"Sixpence None The Richer",song:"Don't Dream It's Over",year:"2008",genre:"Pop"},
{author:"Eminem",song:"Sing For The Moment",year:"2008",genre:"Misc"},
{author:"50 cent feat Justin Timberlake",song:"AYO Technology",year:"2008",genre:""},
{author:"Savage Garden",song:"Break me shake me",year:"2008",genre:"Pop"},
{author:"Savage Garden",song:"Tears of pearls",year:"2008",genre:""},
{author:"Britney Spears",song:"Gimme More",year:"2008",genre:"Other"},
{author:"Akon",song:"I Wanna Fuck You Dirty",year:"2008",genre:"Other"},
{author:"Markt",song:"Area 51",year:"2008",genre:""},
{author:"Mr. Oizo",song:"Flat Beat",year:"2008",genre:"House"},
{author:"R.E.M",song:"Bang And Blame",year:"2008",genre:"Other"},
{author:"Puff Daddy feat Jimmy Page",song:"Come With Me",year:"2008",genre:"Rock"},
{author:"Robbie Williams",song:"By All Means Necessary",year:"2008",genre:"Other"},
{author:"Fragma",song:"Toca Me",year:"2008",genre:"Trance"},
{author:"Propellerheads",song:"Spybreak Short One",year:"2008",genre:"Other"},
{author:"Monster Magnet",song:"Look to ur orb for the warning",year:"2008",genre:"Soundtrack"},
{author:"Neneh Cherry",song:"Woman",year:"2008",genre:"Rock"},
{author:"Neneh Cherry",song:"7 Second",year:"2008",genre:"Rock"},
{author:"Mamas and Papas",song:"House Of The Rising Sun",year:"2005",genre:"Oldies"},
{author:"Lunatic Calm",song:"Leave you far behind",year:"1998",genre:"Soundtrack"},
{author:"Rob Zombie",song:"Dragula",year:"2005",genre:"Soundtrack"},
{author:"Chris Rea",song:"Lookin For The Summer",year:"1994",genre:"Rock"},
{author:"Aerosmith",song:"I Don't Want To Miss A Thing",year:"2005",genre:"Soundtrack"},
{author:"Led Zeppelin",song:"Stairway to Heaven",year:"2005",genre:""},
{author:"Chris Rea",song:"Road To Hell",year:"2000",genre:"Rock"},
{author:"Coolio",song:"Gangstas Paradise",year:"2009",genre:""},
{author:"Arrival",song:"Kazantip",year:"2009",genre:""},
{author:"Darude",song:"Sandstorm",year:"2005",genre:"Dance"},
{author:"Basement Jaxx",song:"Rendez Vu",year:"1978",genre:"Electronic"},
{author:"Sting",song:"Shape Of My Heart",year:"2008",genre:""},
{author:"Jenifer Page",song:"Crush",year:"2008",genre:"Rock"},
{author:"Blue & Elton John",song:"Sorry Seems",year:"2008",genre:"Dream"},
{author:"Cardigans",song:"Erase / Rewind",year:"2008",genre:"Rock"},
{author:"Rob D",song:"Clubbed to Death (kurayamino)",year:"2008",genre:"Soundtrack"},
{author:"Liquido",song:"Narcoric",year:"2008",genre:"Rock"},
{author:"Busta Rhymes",song:"Give it to Me",year:"2008",genre:""},
{author:"Daft Punk",song:"Around the world",year:"2008",genre:"Disco"},
{author:"Christina Aguilera feat Jay z & Foxy",song:"Genie In A Bottle",year:"2008",genre:"Hip"},
{author:"Chris Rea",song:"Josephine",year:"2008",genre:"Rock"},
{author:"Des'ree",song:"You Gotta Be",year:"2008",genre:""},
{author:"Robbie Williams",song:"Supreme",year:"2008",genre:"Pop"},
{author:"David Usher",song:"Black Black Heart",year:"2004",genre:""},
{author:"Cardigans",song:"My Favourite Game",year:"1985",genre:"Alternative"},
{author:"Zombie Nation",song:"KERNKRAFT 400",year:"1985",genre:"Other"},
{author:"Aerosmith",song:"Pink",year:"1985",genre:""},
{author:"Joe Cocker",song:"My father`s son",year:"1985",genre:"Rock"},
{author:"Joan Osborne",song:"One Of Us",year:"2004",genre:"Rock"},
{author:"Eagle Eye Cherry",song:"Save Tonight",year:"2004",genre:"Rock"},
{author:"Tomy Or Zox",song:"My Desire",year:"2004",genre:""},
{author:"R.E.M",song:"Losing My Religion",year:"2003",genre:""},
{author:"Wallflowers",song:"One Headlight",year:"2003",genre:"Other"},
{author:"Creed",song:"Ny sacrifice",year:"2003",genre:"Rock"},
{author:"Larry Mullen & Adam Clayton",song:"Theme From Mission Impossible",year:"2003",genre:""},
{author:"Simply Red",song:"Stars",year:"2008",genre:"Rock"},
{author:"Darren Hayes",song:"Insatiable",year:"2008",genre:""},
{author:"Simply Red",song:"Something Got Me Started",year:"2008",genre:"Blues"},
{author:"Oasis",song:"Go Let It Out",year:"2008",genre:"Pop"},
{author:"Take That",song:"Babe",year:"2008",genre:""},
{author:"Alanis Morissette",song:"Hands Clean",year:"2001",genre:"Rock"},
{author:"Nickelback",song:"This Is How You Remind Me",year:"2001",genre:"Rock"},
{author:"Candy Dulfer & Dave Steward",song:"Lily Was Here",year:"2001",genre:"Rock"},
{author:"Ozzy Osbourne",song:"Mama I Am Coming Home",year:"2001",genre:"Blues"},
{author:"Tito & Tarantula",song:"After Dark",year:"2001",genre:""},
{author:"Bruce Springstein",song:"Streets of Philadelphia",year:"2001",genre:"Rock"},
{author:"Bryan Ferry",song:"Don`t Stop The Dance",year:"2008",genre:"Rock"},
{author:"David Gray White Ladder",song:"Sail Away",year:"2008",genre:"Pop"},
{author:"Diana Ross",song:"Over Yet",year:"2008",genre:"Pop"},
{author:"Kind of Blue",song:"Bitter Blue",year:"2008",genre:"Pop"},
{author:"Belinda Carlisle",song:"California",year:"1996",genre:"Rock"},
{author:"Sheryl Crow",song:"All I Wanna Do",year:"2008",genre:"Rock"},
{author:"Shevaree",song:"Goodnight Moon",year:"2008",genre:"Other"},
{author:"Sixpence None The Richer",song:"Kiss Me",year:"2008",genre:"Christian Rock"},
{author:"Lighthouse Family",song:"Free",year:"2001",genre:""},
{author:"Lighthouse Family",song:"Run",year:"2002",genre:"Pop"},
{author:"Kylie Minogue feat. Nick Cave",song:"Where The Wild Roses Grow",year:"2008",genre:"Rock"},
{author:"Sade",song:"No Ordinary Love",year:"2012",genre:""},
{author:"Elton John",song:"Believe",year:"2008",genre:"Pop"},
{author:"The Calling",song:"Wherever You Will Go",year:"1996",genre:"Rock"},
{author:"Sinead O'connor",song:"Nothing Compares To You",year:"2008",genre:"Rock"},
{author:"Elton John",song:"Blessed",year:"2008",genre:"Rock"},
{author:"Chris Norman",song:"Some Hearts Are Diamonds",year:"2008",genre:"Pop"},
{author:"Black",song:"Wonderful Live",year:"2014",genre:"Rock"},
{author:"Ozzy Osbourne",song:"Dreamer",year:"1982",genre:"Rock"},
{author:"Sum 41",song:"In Too Deep",year:"1982",genre:"Rock"},
{author:"Down Low",song:"About You",year:"1982",genre:""},
{author:"The Boogie Pimps",song:"Somebody to Love",year:"2007",genre:"Top 40"},
{author:"Meat Loaf",song:"I'd Do Anything For Love",year:"1982",genre:"Rock"},
{author:"Right Said Fred",song:"I'm Too Sexy",year:"2007",genre:""},
{author:"Justin Timberlake",song:"Sexy Back",year:"1980",genre:"R&B"},
{author:"Giorgos Mazonakis",song:"Nikotini",year:"1992",genre:"Ethnic"},
{author:"Giorgos Mazonakis",song:"Amanes",year:"2007",genre:"Blues"},
{author:"DJ Sash",song:"Adelante",year:"1993",genre:"Trance"},
{author:"The Prodigy & Tom Morello",song:"One Man Army",year:"2007",genre:"Soundtrack"},
{author:"Giorgos Mazonakis",song:"Tu gucci forema",year:"2003",genre:""},
{author:"Beatfreakz",song:"Somebody's Watching Me",year:"2007",genre:"Other"},
{author:"Guy",song:"Groove Me",year:"1982",genre:"Soundtrack"},
{author:"Mylene Farmer",song:"California",year:"2008",genre:"Other"},
{author:"Backstreet boys",song:"Incomplete",year:"2008",genre:"Pop"},
{author:"Queen",song:"Jelousy",year:"2006",genre:""},
{author:"Darren Hayes",song:"Strange Relationship",year:"1999",genre:"Crossover"},
{author:"AFI",song:"Head Like A Hole (Bonus Track)",year:"1999",genre:"Soundtrack"},
{author:"666",song:"El fuego",year:"1956",genre:"Rave"},
{author:"Pain",song:"Shut Your Mouth",year:"1945",genre:"Rock"},
{author:"Raze",song:"Break 4 Love",year:"1999",genre:"Soundtrack"},
{author:"Joey Negro",song:"Make a Move On Me",year:"1999",genre:"Other"},
{author:"Supermode",song:"Tell Me Why",year:"1999",genre:"Electronic"},
{author:"Michael Jackson",song:"Billy Jean",year:"2008",genre:""},
{author:"Rage Against The Machine",song:"Killing In The Name",year:"2008",genre:"Soundtrack"},
{author:"James Blunt",song:"You`re Beautiful",year:"2004",genre:"Other"},
{author:"Karmah",song:"Just Be Good To Me",year:"2017",genre:"Electronic"},
{author:"Lordz of Brooklyn",song:"Lake of Fire",year:"2014",genre:""},
{author:"Ian Carey ft. Michelle Shellers",song:"Keep On Rising (Radio Mix)",year:"2008",genre:"House"},
{author:"Jay Sean",song:"Ride It",year:"2008",genre:"Other"},
{author:"Madcon",song:"Beggin",year:"2008",genre:""},
{author:"Madonna",song:"Give It 2 Me (Radio Edit)",year:"2006",genre:""},
{author:"Pussycat Dolls",song:"Buttons",year:"1997",genre:"Pop"},
{author:"R.I.O.",song:"Shine On (Original Mix)",year:"1998",genre:"House"},
{author:"Will.I.Am",song:"Heartbreaker",year:"2000",genre:""}
]}
export default data